import type { HookCategory } from "./types";

// All hook text is verbatim from the Plutus Media Viral Hook Vault
// (Section 2: 300 Proven UGC Hooks). Only the category summaries and
// "why it works for Rork" notes are added commentary. Hooks that are
// clearly about non-app categories (fitness, therapy, diet, etc.)
// have been filtered out — everything here applies to an app/SaaS/AI tool.

export const hookCategories: HookCategory[] = [
  {
    slug: "curious-creator",
    title: "The Curious Creator",
    summary:
      "These hooks trigger curiosity and disbelief — the viewer HAS to keep watching.",
    whyItWorks:
      "Rork genuinely does the unbelievable — one prompt, a real App Store app. This category is the bullseye. Pair with reaction / snap-swap / screen-demo formats.",
    hooks: [
      { text: "How is this legal...?" },
      { text: "Wait this can't be real..." },
      { text: "Yo what the f***...?" },
      { text: "This should be illegal but..." },
      { text: "I'm so confused right now..." },
      { text: "Wait... how does this even work?" },
      { text: "This makes no sense..." },
      { text: "I don't understand how this is possible..." },
      { text: "Okay but actually how...?" },
      { text: "This broke my brain..." },
      { text: "I've been staring at this for 10 minutes..." },
      { text: "Someone explain this to me..." },
      { text: "This can't be real right...?" },
      { text: "What am I even looking at...?" },
      { text: "Hold on... WHAT?" },
      { text: "I'm sorry but how...?" },
      { text: "This is actually insane..." },
      { text: "Wait did that just...?" },
      { text: "No way this is real..." },
      { text: "I refuse to believe this works..." },
      { text: "This has to be fake..." },
      { text: "Someone tell me I'm not crazy..." },
      { text: "Okay I need answers..." },
      { text: "This is actually breaking my brain..." },
      { text: "I can't stop watching this..." },
      { text: "Wait... that's not possible..." },
      { text: "How is nobody talking about this...?" },
      { text: "This is the weirdest thing I've seen..." },
      { text: "I don't even know what to say..." },
      { text: "This shouldn't exist but here we are..." },
    ],
  },
  {
    slug: "gatekeeper",
    title: "The Gatekeeper",
    summary:
      "These hooks create a feeling of exclusivity — you're sharing something forbidden.",
    whyItWorks:
      "Weaker fit than Curious Creator, but works for the dev/agency angle — imagine your developer or agency quietly fuming that Rork exists. Curated to the ones that map to that energy.",
    hooks: [
      { text: "My developer told me never to share this..." },
      { text: "Deleted this 3 times but you need to see..." },
      { text: "I'm not supposed to show you this..." },
      { text: "They told me to keep this quiet..." },
      { text: "They don't want you to know this..." },
      { text: "This is supposed to be internal only..." },
      { text: "I shouldn't be sharing this but..." },
      { text: "This was behind a paywall until now..." },
      { text: "They're going to take this down soon..." },
      { text: "This violates company policy but..." },
      { text: "I'm posting this before I get caught..." },
      { text: "This leaks their entire strategy..." },
      { text: "I have insider access and this is wild..." },
    ],
  },
  {
    slug: "someone-showed-me",
    title: "Someone Showed Me…",
    summary:
      "Social proof through a trusted person — builds instant credibility.",
    whyItWorks:
      "Huge fit. Works for every Rork audience — students (\"my roommate\"), founders (\"my co-founder\"), devs (\"my developer friend\"). Keep the delivery casual, not salesy.",
    hooks: [
      { text: "My friend showed me this and I'm obsessed..." },
      { text: "My roommate just showed me this..." },
      { text: "My coworker wouldn't stop talking about this..." },
      { text: "My boss uses this and won't shut up about it..." },
      { text: "My professor recommended this in class..." },
      { text: "My team lead showed me this yesterday..." },
      { text: "My mentor sent me this last week..." },
      { text: "My client showed me this during a call..." },
      { text: "My business partner found this and..." },
      { text: "My investor uses this daily..." },
      { text: "My co-founder showed me this..." },
      { text: "My manager swears by this..." },
      { text: "My CTO introduced me to this..." },
      { text: "My designer showed me this tool..." },
      { text: "My developer friend built this and..." },
      { text: "My marketing lead uses this for everything..." },
      { text: "My sales team discovered this..." },
      { text: "My assistant found this and now..." },
      { text: "My CEO uses this in every meeting..." },
      { text: "My advisor recommended this..." },
      { text: "My dad showed me this app..." },
      { text: "My brother uses this for his business..." },
      { text: "My sister works there and showed me..." },
      { text: "My cousin built this and..." },
      { text: "My girlfriend found this and..." },
      { text: "My best friend sent me this..." },
      { text: "My old colleague showed me..." },
      { text: "My ex-boss uses this now and..." },
      { text: "My classmate from [school] built this..." },
      { text: "My mastermind group uses this..." },
    ],
  },
  {
    slug: "impossible-claim",
    title: "The Impossible Claim",
    summary:
      "Bold, specific results that stop the scroll. The more specific the number, the more believable.",
    whyItWorks:
      "This is Rork's core 2025 viral format (\"I made 7 apps in a weekend\"). Filtered to the ones that map to apps, money, and work — not fitness or lifestyle.",
    hooks: [
      { text: "I built an app in 10 minutes..." },
      { text: "This app does in 10 seconds what takes 10 hours..." },
      { text: "I went from broke to $10K/month using this..." },
      { text: "I quit my 9-5 after using this for 30 days..." },
      { text: "I built a $100K business with just this app..." },
      { text: "This doubled my income in 90 days..." },
      { text: "I automated my entire side hustle with this..." },
      { text: "I turned $500 into $10K using this app..." },
    ],
  },
  {
    slug: "regret-reveal",
    title: "The Regret Reveal",
    summary:
      "The viewer feels the pain of NOT knowing sooner — creates urgency to act now.",
    whyItWorks:
      "Perfect for the non-technical founder audience. Anyone who's been burned by a dev agency, a Fiverr freelancer, or months of tutorials is the target.",
    hooks: [
      { text: "I wasted $10K before finding this..." },
      { text: "3 years and nobody told me about this..." },
      { text: "Why didn't anyone show me this sooner..." },
      { text: "I could've saved 2 years if I knew this..." },
      { text: "I spent $50K on courses before finding this free app..." },
      { text: "5 years of struggle ended when I found this..." },
      { text: "I wish I had this in college..." },
      { text: "I paid a developer $20K for what this does for free..." },
      { text: "10 years and I just found out about this..." },
      { text: "I burned $100K on ads before discovering this..." },
      { text: "I suffered for 6 months before someone showed me this..." },
      { text: "Why did it take me this long to find this..." },
      { text: "I spent 4 years doing it the hard way..." },
      { text: "I lost $50K because nobody told me about this..." },
      { text: "I could've retired 5 years earlier with this..." },
      { text: "I paid $500/month for what this does better..." },
      { text: "I wasted my entire 20s not knowing this..." },
      { text: "6 months of pain before I discovered this..." },
      { text: "I would've kept my business if I had this..." },
      { text: "I dropped $30K on a bootcamp before finding this..." },
      { text: "3 failed startups before someone told me about this..." },
      { text: "I could've avoided burnout if I knew this existed..." },
      { text: "I spent 10 years broke before finding this..." },
      { text: "Why isn't this taught in school..." },
      { text: "I fired my entire team before discovering this..." },
      { text: "I almost gave up before finding this app..." },
      { text: "7 years of trial and error vs 7 days with this..." },
      { text: "I rebuilt my life after finding this..." },
    ],
  },
  {
    slug: "comparison",
    title: "The Comparison",
    summary:
      "Positions your product as the superior alternative — viewers love a clear winner.",
    whyItWorks:
      "Rork's SEO already competes with Cursor, Lovable, Bolt, Flutterflow. Creators should name those tools on camera — that's how the algorithm finds you when viewers search.",
    hooks: [
      { text: "I tried 15 apps, this is the only one that worked..." },
      { text: "Everyone uses ChatGPT, I use this instead..." },
      { text: "Tested 20 productivity apps, only this one stuck..." },
      { text: "Everyone uses Google Docs, this is 10x better..." },
      { text: "I ditched my $1K/month agency for this app..." },
      { text: "Everyone's paying for courses, I learned everything from this..." },
      { text: "Tried Photoshop for years, this does it in seconds..." },
      { text: "Everyone's using Figma, designers are switching to this..." },
      { text: "I canceled my $50/month subscription for this free alternative..." },
      { text: "I replaced my $500 course with this free app..." },
    ],
  },
  {
    slug: "unintentional-find",
    title: "The Unintentional Find",
    summary:
      "The \"happy accident\" story — feels authentic because the discovery wasn't planned.",
    whyItWorks:
      "Low-stakes, high-trust. Great opener for longer narrative videos where the viewer rides along with your discovery. Zero sales energy.",
    hooks: [
      { text: "I wasn't even looking for this but..." },
      { text: "Downloaded this by mistake and now I can't delete it..." },
      { text: "Accidentally discovered this and it changed everything..." },
      { text: "I clicked the wrong ad and found this..." },
      { text: "Stumbled on this at 3am and now..." },
      { text: "I was looking for something else and found this instead..." },
      { text: "Accidentally opened this app and..." },
      { text: "I downloaded this as a joke but..." },
      { text: "Found this by accident and now I use it daily..." },
      { text: "I wasn't supposed to find this but..." },
      { text: "Clicked on this randomly and it saved my life..." },
      { text: "I discovered this while procrastinating and..." },
      { text: "Found this in the comments of another video..." },
      { text: "I was bored and downloaded this, now..." },
      { text: "Accidentally swiped on this and it's a game changer..." },
      { text: "I found this while doom scrolling at 2am..." },
      { text: "Downloaded this for fun, turns out..." },
      { text: "I wasn't planning on trying this but..." },
      { text: "Found this while looking for something completely different..." },
      { text: "I discovered this during a random Google search..." },
      { text: "Clicked on this thinking it was something else..." },
      { text: "I found this in my spam folder and..." },
      { text: "Downloaded this on a whim and now..." },
      { text: "I was skeptical but tried it anyway and..." },
      { text: "Found this while deleting apps and kept only this one..." },
      { text: "I ignored this for months until I actually tried it..." },
      { text: "Discovered this while cleaning out my phone..." },
      { text: "I almost deleted this but opened it first and..." },
      { text: "Found this in my downloads from 6 months ago..." },
      { text: "I wasn't even trying to find a solution and this showed up..." },
    ],
  },
  {
    slug: "ragebait-flex",
    title: "The Ragebait Flex",
    summary:
      "Warning: may get hate comments, but will go viral. Use with caution.",
    whyItWorks:
      "Rork wants to test \"Day in the life of a mobile app entrepreneur.\" This category is where those hooks live. Filtered to work/business/money — skipped lifestyle (gym, diet, languages).",
    hooks: [
      { text: "How I work 4 hours a day without burning out..." },
      { text: "POV: You just made $10K in your sleep..." },
      { text: "Day in my life using only this app..." },
      { text: "How I travel full-time and still run my business..." },
      { text: "I haven't set an alarm in 6 months because of this..." },
      { text: "How I automate my entire income with one app..." },
      { text: "POV: You just quit your 9-5 using this..." },
      { text: "Living my dream life because I found this app..." },
      { text: "I work from my phone and make 6 figures with this..." },
      { text: "POV: You just paid off all your debt with this..." },
      { text: "My entire morning routine is just this app..." },
      { text: "How I manage 3 businesses with zero stress..." },
      { text: "I retired at 30 because of this app..." },
      { text: "Living the laptop lifestyle thanks to this..." },
      { text: "POV: You just automated your entire side hustle..." },
      { text: "I haven't been stressed in 90 days because of this..." },
      { text: "How I make passive income with just my phone..." },
      { text: "Running a 7-figure business from this one app..." },
      { text: "How I travel 6 months a year and work 20 hours a week..." },
      { text: "I deleted all my apps except this one..." },
      { text: "Living proof you don't need a degree with this app..." },
      { text: "POV: You just hit your first $100K year using this..." },
      { text: "I replaced my entire team with this app..." },
      { text: "How I wake up excited every day using this..." },
      { text: "Running my dream business from my bedroom with this..." },
      { text: "I haven't worked a 'real job' in 2 years thanks to this..." },
    ],
  },
  {
    slug: "authority-endorsement",
    title: "The Authority Endorsement",
    summary:
      "Borrow credibility from professionals and authority figures.",
    whyItWorks:
      "Most of Plutus's Authority list is medical (dentist, doctor, therapist) which doesn't fit. Filtered to the tech/business roles that actually apply to Rork.",
    hooks: [
      { text: "As a developer, this is the only app I actually use..." },
      { text: "As a marketer, I've never seen an app do this..." },
      { text: "As a designer, this replaced my entire workflow..." },
      { text: "As a product manager, this is how we scaled to $10M..." },
      { text: "As an engineer, this solved what code couldn't..." },
      { text: "As a founder, this is the only app I open daily..." },
      { text: "As a VC, I invest in companies using this..." },
      { text: "As a CEO, this is non-negotiable for my team..." },
    ],
  },
  {
    slug: "trend-hijack",
    title: "The Trend Hijack",
    summary:
      "Ride existing viral trends — but make them about your product.",
    whyItWorks:
      "You borrow the algorithm's existing momentum. Viewers already know the format; you just substitute Rork into the punchline.",
    hooks: [
      { text: "Rumors are true..." },
      { text: "Using the 'hear me out' trend to show you this app..." },
      { text: "Doing the 'get ready with me' but make it productivity..." },
      { text: "The 'tell me without telling me' version for this app..." },
      { text: "POV trend but it's actually useful this time..." },
      { text: "Using the 'day in the life' trend to flex this app..." },
      { text: "The 'things I wish I knew sooner' trend led me here..." },
      { text: "Caught in 4K using this app instead of working..." },
      { text: "The 'millionaire morning routine' but it's just this app..." },
      { text: "Using the 'what's in my bag' trend but it's what's on my phone..." },
      { text: "The 'rate my setup' trend but showing this instead..." },
      { text: "Doing the 'unboxing' trend with a digital product..." },
      { text: "Using the 'before and after' trend but for my productivity..." },
      { text: "The 'things that just make sense' trend brought me here..." },
      { text: "Doing the 'hot take' trend: this app is underrated..." },
      { text: "The 'green screen' trend showing my app analytics..." },
      { text: "Using the 'storytime' format to explain how this saved me..." },
      { text: "The 'wait for it' trend but it's actually worth the wait..." },
      { text: "Doing the 'duet' trend but with my own app results..." },
      { text: "The 'photo dump' trend but it's screenshots of this app..." },
      { text: "Using the 'transition' trend to show before/after..." },
      { text: "The 'top 3' trend but it's features of this one app..." },
      { text: "Doing the 'ranking' trend for apps in this category..." },
      { text: "The 'this or that' trend but it's old way vs this app..." },
      { text: "Using the 'put a finger down' trend for app users..." },
      { text: "The 'outfit of the day' but it's my app stack..." },
      { text: "Doing the 'reset routine' trend with just this app..." },
      { text: "The 'glow up' trend but it's my business metrics..." },
    ],
  },
];
