// AUTO-GENERATED from ViewTrack + data/curation.json.
// Pins (manual curation) come first, then bucket top videos by views,
// excluded IDs removed, analyzed videos bubbled up.
import type { VideoExample } from "./types";

export const rorkVideos: Record<string, VideoExample[]> = {
  "talking-head": [
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVCnMwriS9V/",
    id: "DVCnMwriS9V",
    dbId: "instagram_instagram_ernestosoftware_DVCnMwriS9V",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVCnMwriS9V.jpg",
    caption: "Comment “Rork” and I’ll send you a free guide 🫡 #coding #vibecoding #aiapps",
    views: 1457090,
    creator: "@ernestosoftware",
    creatorUrl: "https://instagram.com/ernestosoftware",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reels/DWhawSnAVrj/",
    id: "DWhawSnAVrj",
    dbId: "0MwTYF1qGts5sBXjxHxl",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_3864487622986521315_thumb.jpg",
    caption: "used to pray for times like this🥲comment LYRC and i’ll send u the site (deleting soon)",
    views: 2016774,
    creator: "@byeloya",
    creatorUrl: "https://instagram.com/byeloya",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DR2cI7YDLAk/",
    id: "DR2cI7YDLAk",
    dbId: "instagram_instagram_randomusefulwebsites_DR2cI7YDLAk",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DR2cI7YDLAk.jpg",
    caption: "Unlock human anatomy like never before! 🧠🔬 Dive into interactive 3D models with smooth animations that make learning biology, medicine, or fitness insanely fun ",
    views: 282297,
    creator: "@randomusefulwebsites",
    creatorUrl: "https://instagram.com/randomusefulwebsites",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DTVN21DCDXO/",
    id: "DTVN21DCDXO",
    dbId: "instagram_instagram_promptingbad_DTVN21DCDXO",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DTVN21DCDXO.jpg",
    caption: "Comment \"MUSIC\" and I'll send you the link! #websites #fyp #musicgpt #aimusic",
    views: 214376,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW7q15jDKSD/",
    id: "DW7q15jDKSD",
    dbId: "instagram_instagram_lockinwzining_DW7q15jDKSD",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW7q15jDKSD.jpg",
    caption: "Comment Seaweed and I’ll send 😛 Make money while eating seaweed!! #sidequest #money #sidehustle #sidehustleforbegginers #sidehustlesuccess  Would you try this?",
    views: 122825,
    creator: "@lockinwzining",
    creatorUrl: "https://instagram.com/lockinwzining",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWJb-TpCDKq/",
    id: "DWJb-TpCDKq",
    dbId: "instagram_instagram_promptingbad_DWJb-TpCDKq",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWJb-TpCDKq.jpg",
    caption: "Comment MUSIC and I'll send you the link!! #websites #musicgpt #aimusic",
    views: 95933,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DTaU4_UiOev/",
    id: "DTaU4_UiOev",
    dbId: "instagram_instagram_promptingbad_DTaU4_UiOev",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DTaU4_UiOev.jpg",
    caption: "Comment \"ABACUS\" and I'll send you the link!  Or check it out in my BIO! #websites #abacus #chatllm #abacusai",
    views: 89502,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DUDh-HICD5E/",
    id: "DUDh-HICD5E",
    dbId: "instagram_instagram_promptingbad_DUDh-HICD5E",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DUDh-HICD5E.jpg",
    caption: "Comment \"GAMBO\" and I'll send you the link! #websites #gaming #gambo #gamboai",
    views: 89081,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVolxSqjMtS/",
    id: "DVolxSqjMtS",
    dbId: "instagram_instagram_randomusefulwebsites_DVolxSqjMtS",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVolxSqjMtS.jpg",
    caption: "Random websites, Part 95 🎮 — this site lets you download tons of games completely free and legal. From indie titles to open‑source projects and older classics t",
    views: 82199,
    creator: "@randomusefulwebsites",
    creatorUrl: "https://instagram.com/randomusefulwebsites",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DT2rm23CNEd/",
    id: "DT2rm23CNEd",
    dbId: "instagram_instagram_promptingbad_DT2rm23CNEd",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DT2rm23CNEd.jpg",
    caption: "Comment “SORA” and I'll DM yout the link! You can also find it in my BIO. #websites #fyp #abacusai#chatllm #ai",
    views: 73276,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DTyKQ0XDNBz/",
    id: "DTyKQ0XDNBz",
    dbId: "instagram_instagram_randomusefulwebsites_DTyKQ0XDNBz",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DTyKQ0XDNBz.jpg",
    caption: "Random websites you NEED to try! Part 81 🚀🍿 This ultimate streaming vault = Netflix + Amazon Prime beaten. Watch ANY movie/TV show FREE — latest blockbusters, s",
    views: 71486,
    creator: "@randomusefulwebsites",
    creatorUrl: "https://instagram.com/randomusefulwebsites",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DR70rdnjCFj/",
    id: "DR70rdnjCFj",
    dbId: "instagram_instagram_randomusefulwebsites_DR70rdnjCFj",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DR70rdnjCFj.jpg",
    caption: "Discover the ultimate treasure trove of customizable React components! ⚛️✨ Pick any component, tweak parameters, and get instant production-ready code — no logi",
    views: 70295,
    creator: "@randomusefulwebsites",
    creatorUrl: "https://instagram.com/randomusefulwebsites",
  },
  ],
  "snapchat-hook-reaction": [
  {
    platform: "tiktok",
    url: "https://www.tiktok.com/@builtbygianni/video/7624955123973819678",
    id: "7624955123973819678",
    dbId: "tiktok_tiktok_builtbygianni_7624955123973819678",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/tiktok_7624955123973819678.jpg",
    caption: "#webild #ai #websites #websitebuilder #claude",
    views: 661198,
    creator: "@builtbygianni",
    creatorUrl: "https://tiktok.com/@builtbygianni",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVCnMwriS9V/",
    id: "DVCnMwriS9V",
    dbId: "instagram_instagram_ernestosoftware_DVCnMwriS9V",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVCnMwriS9V.jpg",
    caption: "Comment “Rork” and I’ll send you a free guide 🫡 #coding #vibecoding #aiapps",
    views: 1457090,
    creator: "@ernestosoftware",
    creatorUrl: "https://instagram.com/ernestosoftware",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVt-W2iiYeB/",
    id: "DVt-W2iiYeB",
    dbId: "instagram_instagram_ernestosoftware_DVt-W2iiYeB",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVt-W2iiYeB.jpg",
    caption: "Comment “Rork” and I’ll send you a detailed guide #coding #vibecoding #aiapps",
    views: 19384,
    creator: "@ernestosoftware",
    creatorUrl: "https://instagram.com/ernestosoftware",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWHpTa6iSpo/",
    id: "DWHpTa6iSpo",
    dbId: "instagram_instagram_ernestosoftware_DWHpTa6iSpo",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWHpTa6iSpo.jpg",
    caption: "Comment “arcads” and I’ll send you a free guide #coding #ai #apps #b2c #onlinemoney",
    views: 8157,
    creator: "@ernestosoftware",
    creatorUrl: "https://instagram.com/ernestosoftware",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DXCtE7oieD1/",
    id: "DXCtE7oieD1",
    dbId: "instagram_instagram_ernestosoftware_DXCtE7oieD1",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DXCtE7oieD1.jpg",
    caption: "Comment “Rork” and I’ll send you the link #b2c #ai #apps #coding #vibecoding",
    views: 4094,
    creator: "@ernestosoftware",
    creatorUrl: "https://instagram.com/ernestosoftware",
  },
  ],
  "reaction-plus-demo": [
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVEFOZNEvy9/",
    id: "DVEFOZNEvy9",
    dbId: "instagram_instagram_jakeezytech_DVEFOZNEvy9",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVEFOZNEvy9.jpg",
    caption: "Websites that even Google won’t tell you Free 4k Live wallpapers #pc #wallpapers",
    views: 2696830,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWpUiI9CuE2/",
    id: "DWpUiI9CuE2",
    dbId: "instagram_instagram_vibingwithxavierr_DWpUiI9CuE2",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWpUiI9CuE2.jpg",
    caption: "here's a free app that helps you discover new music! #spotify #findingmusic #ilovemusic",
    views: 350134,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DTK2I16iPJ0/",
    id: "DTK2I16iPJ0",
    dbId: "instagram_instagram_promptingbad_DTK2I16iPJ0",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DTK2I16iPJ0.jpg",
    caption: "This website is a full library of free learning tools for kids #websites #homeschool #education #learning",
    views: 347448,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DXCZozZEfJc/",
    id: "DXCZozZEfJc",
    dbId: "instagram_instagram_softwarewithnick_DXCZozZEfJc",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DXCZozZEfJc.jpg",
    caption: "Free Data Engineering Course 😎 This 9 week course will run you through all of the tools you need to be proficient at to become a data engineer. These modules co",
    views: 86324,
    creator: "@softwarewithnick",
    creatorUrl: "https://instagram.com/softwarewithnick",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW9_IjBAgO2/",
    id: "DW9_IjBAgO2",
    dbId: "instagram_instagram_softwarewithnick_DW9_IjBAgO2",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW9_IjBAgO2.jpg",
    caption: "My new favorite free tool 😎 This new tool is the best. It’s essentially VS code and RStudio wrapped into one, giving you an easy and interactive way to write yo",
    views: 35808,
    creator: "@softwarewithnick",
    creatorUrl: "https://instagram.com/softwarewithnick",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW3_FGmDpEF/",
    id: "DW3_FGmDpEF",
    dbId: "instagram_instagram_softwarewithnick_DW3_FGmDpEF",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW3_FGmDpEF.jpg",
    caption: "Free data access 😎 Obtaining data for your project can often times prove to be a difficult task. With this tool you can find pretty much any data you need compl",
    views: 15051,
    creator: "@softwarewithnick",
    creatorUrl: "https://instagram.com/softwarewithnick",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW13lgoClWO/",
    id: "DW13lgoClWO",
    dbId: "instagram_instagram_vibingwithxavierr_DW13lgoClWO",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW13lgoClWO.jpg",
    caption: "Free app that's like Tinder, but for music..🤯 #spotify #findingmusic #ilovemusic",
    views: 13657,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DXCZ-EoEb-R/",
    id: "DXCZ-EoEb-R",
    dbId: "instagram_instagram_softwarewithnick_DXCZ-EoEb-R",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DXCZ-EoEb-R.jpg",
    caption: "Useful Free Data Analyst Resource 😎 As someone who codes primarily in R, I still have times where I need to use Python. This 1 to 1 translation from R commands ",
    views: 13571,
    creator: "@softwarewithnick",
    creatorUrl: "https://instagram.com/softwarewithnick",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DXC1woSivTa/",
    id: "DXC1woSivTa",
    dbId: "instagram_instagram_vibingwithxavierr_DXC1woSivTa",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DXC1woSivTa.jpg",
    caption: "Why didnt I know about this free app before 🤯 #findingmusic #spotify #ilovemusic",
    views: 9621,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW-DBwGigRo/",
    id: "DW-DBwGigRo",
    dbId: "instagram_instagram_vibingwithxavierr_DW-DBwGigRo",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW-DBwGigRo.jpg",
    caption: "why is nobody talking about this free app?! 🤯 #spotify #findingmusic #ilovemusic",
    views: 9328,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW2m-azkRJF/",
    id: "DW2m-azkRJF",
    dbId: "instagram_instagram_vibingwithxavierr_DW2m-azkRJF",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW2m-azkRJF.jpg",
    caption: "Free app that let's you discover new artists and music! 🤯 #spotify #findingmusic #ilovemusic",
    views: 5927,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW4rriyCmBF/",
    id: "DW4rriyCmBF",
    dbId: "instagram_instagram_vibingwithxavierr_DW4rriyCmBF",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW4rriyCmBF.jpg",
    caption: "free app that let's you find new artists and songs! #spotify #findingmusic #ilovemusic",
    views: 5828,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  ],
  "split-screen": [
  ],
  "building-page": [
  {
    platform: "tiktok",
    url: "https://www.tiktok.com/@builtbygianni/video/7624955123973819678",
    id: "7624955123973819678",
    dbId: "tiktok_tiktok_builtbygianni_7624955123973819678",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/tiktok_7624955123973819678.jpg",
    caption: "#webild #ai #websites #websitebuilder #claude",
    views: 661198,
    creator: "@builtbygianni",
    creatorUrl: "https://tiktok.com/@builtbygianni",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVSfTZFjWBr/",
    id: "DVSfTZFjWBr",
    dbId: "instagram_instagram_joelstudieslate_DVSfTZFjWBr",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVSfTZFjWBr.jpg",
    caption: "don’t get caught with these sites 🫣 #college #website #school #ai",
    views: 10751508,
    creator: "@joelstudieslate",
    creatorUrl: "https://instagram.com/joelstudieslate",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVXdYMoAF-R/",
    id: "DVXdYMoAF-R",
    dbId: "instagram_instagram_alitrek0_DVXdYMoAF-R",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVXdYMoAF-R.jpg",
    caption: "Website that will make BOOYAH Part 5 #ifixit #website #tech #ai #aitools",
    views: 3864772,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWkGdsPk5Eh/",
    id: "DWkGdsPk5Eh",
    dbId: "instagram_instagram_alitrek0_DWkGdsPk5Eh",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWkGdsPk5Eh.jpg",
    caption: "Website that makes BOOYAH Part 10 #games #softwares #apps #tech #ai",
    views: 1387988,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DSiO1xMjjqW/",
    id: "DSiO1xMjjqW",
    dbId: "instagram_instagram_setupspawn_DSiO1xMjjqW",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DSiO1xMjjqW.jpg",
    caption: "Is this black magic? I found this tool that can extract any sound from a video or audio file. I think it may be limited to 20 seconds but it does have the model",
    views: 985585,
    creator: "@setupspawn",
    creatorUrl: "https://instagram.com/setupspawn",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVRF0A4DQIR/",
    id: "DVRF0A4DQIR",
    dbId: "instagram_instagram_setupspawn_DVRF0A4DQIR",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVRF0A4DQIR.jpg",
    caption: "Did you know ai could do this? You need to be careful about how you redact information on your pictures and files. People may be able to easily read it. Enjoy! ",
    views: 707322,
    creator: "@setupspawn",
    creatorUrl: "https://instagram.com/setupspawn",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWjRmmRiicN/",
    id: "DWjRmmRiicN",
    dbId: "instagram_instagram_setupspawn_DWjRmmRiicN",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWjRmmRiicN.jpg",
    caption: "Is this ai chatbot better than ChatGPT? I found this site that may be the future of ai chatbots. You can get legit answers from real human ais. What did you ask",
    views: 559524,
    creator: "@setupspawn",
    creatorUrl: "https://instagram.com/setupspawn",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVMTXPcgNo-/",
    id: "DVMTXPcgNo-",
    dbId: "instagram_instagram_alitrek0_DVMTXPcgNo-",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVMTXPcgNo-.jpg",
    caption: "Website that will BOOYAH ✨ #website #carfix #tech #ai #aitools",
    views: 462307,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DU6aAiZAEmu/",
    id: "DU6aAiZAEmu",
    dbId: "instagram_instagram_alitrek0_DU6aAiZAEmu",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DU6aAiZAEmu.jpg",
    caption: "Fun Website Part 1  #website #tech #techtips #ai #reels",
    views: 273522,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVsFX2YgL7m/",
    id: "DVsFX2YgL7m",
    dbId: "instagram_instagram_alitrek0_DVsFX2YgL7m",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVsFX2YgL7m.jpg",
    caption: "Website that will make BOOYAH ✨  #website #tech #ai #aitools #reels",
    views: 257709,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVdrM_8iM-D/",
    id: "DVdrM_8iM-D",
    dbId: "instagram_instagram_promptingbad_DVdrM_8iM-D",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVdrM_8iM-D.jpg",
    caption: "Bypass any AI detectors!!! #evadegpt #chatgpt #aihumanizer #ai",
    views: 172332,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVOM1b2iNlU/",
    id: "DVOM1b2iNlU",
    dbId: "instagram_instagram_promptingbad_DVOM1b2iNlU",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVOM1b2iNlU.jpg",
    caption: "Rent your body to AI agents! #websites #goviral #fyp #AI",
    views: 164469,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  ],
  "top-three-websites": [
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWwjk-NiY2S/",
    id: "DWwjk-NiY2S",
    dbId: "instagram_instagram_numberswithxavier_DWwjk-NiY2S",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWwjk-NiY2S.jpg",
    caption: "websites you HAVE to know about 🤫 #websites #study #math",
    views: 249329,
    creator: "@numberswithxavier",
    creatorUrl: "https://instagram.com/numberswithxavier",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW1rjnUiY25/",
    id: "DW1rjnUiY25",
    dbId: "instagram_instagram_numberswithxavier_DW1rjnUiY25",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW1rjnUiY25.jpg",
    caption: "websites i’m not gatekeeping anymore 👀 #websites #math #study",
    views: 18125,
    creator: "@numberswithxavier",
    creatorUrl: "https://instagram.com/numberswithxavier",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWovS-ICnGR/",
    id: "DWovS-ICnGR",
    dbId: "instagram_instagram_numberswithxavier_DWovS-ICnGR",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWovS-ICnGR.jpg",
    caption: "TOP 3 websites to make your academic comeback 😳#websites #study #math",
    views: 4605,
    creator: "@numberswithxavier",
    creatorUrl: "https://instagram.com/numberswithxavier",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DU5p8u0iD4B/",
    id: "DU5p8u0iD4B",
    dbId: "instagram_instagram_promptingbad_DU5p8u0iD4B",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DU5p8u0iD4B.jpg",
    caption: "3 websites to cure your boredom! #websites #goviral #fyp #minecraft #cs",
    views: 8546842,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DViyVtvCFaW/",
    id: "DViyVtvCFaW",
    dbId: "instagram_instagram_promptingbad_DViyVtvCFaW",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DViyVtvCFaW.jpg",
    caption: "3 websites to cure your boredom!! #websites #goviral #fyp #websitestocureboredom",
    views: 3039060,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWG4sBWCCGc/",
    id: "DWG4sBWCCGc",
    dbId: "instagram_instagram_promptingbad_DWG4sBWCCGc",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWG4sBWCCGc.jpg",
    caption: "3 powerful websites you should know! #websites #goviral #fyppage",
    views: 2682018,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVLp6SgCPC9/",
    id: "DVLp6SgCPC9",
    dbId: "instagram_instagram_promptingbad_DVLp6SgCPC9",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVLp6SgCPC9.jpg",
    caption: "3 powerful websites you should know!! #websites #goviral #fyppage #languagelearning #bookgram #coding",
    views: 1560270,
    creator: "@promptingbad",
    creatorUrl: "https://instagram.com/promptingbad",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVzDDQVkoUt/",
    id: "DVzDDQVkoUt",
    dbId: "instagram_instagram_1ukas.online_DVzDDQVkoUt",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVzDDQVkoUt.jpg",
    caption: "3 websites you need right now #college #collegehacks #studytools",
    views: 9334172,
    creator: "@1ukas.online",
    creatorUrl: "https://instagram.com/1ukas.online",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DUqHcZFEfIR/",
    id: "DUqHcZFEfIR",
    dbId: "instagram_instagram_billysosmart_DUqHcZFEfIR",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DUqHcZFEfIR.jpg",
    caption: "3 websites you NEED to start using #college #collegehacks #studytools",
    views: 6878498,
    creator: "@billysosmart",
    creatorUrl: "https://instagram.com/billysosmart",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWS7K5QE9lY/",
    id: "DWS7K5QE9lY",
    dbId: "instagram_instagram_alitrek0_DWS7K5QE9lY",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWS7K5QE9lY.jpg",
    caption: "3 Website that feels iilegal to know #tech #techtips #techtricks #website #ai #aitools #reels #reelsi̇nstagram",
    views: 1929001,
    creator: "@alitrek0",
    creatorUrl: "https://instagram.com/alitrek0",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWRfzh2DfcG/",
    id: "DWRfzh2DfcG",
    dbId: "instagram_instagram_1ukas.online_DWRfzh2DfcG",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWRfzh2DfcG.jpg",
    caption: "3 websites you need right now #college #collegehacks #studytools",
    views: 1375652,
    creator: "@1ukas.online",
    creatorUrl: "https://instagram.com/1ukas.online",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWEVqXQjfZ7/",
    id: "DWEVqXQjfZ7",
    dbId: "instagram_instagram_1ukas.online_DWEVqXQjfZ7",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWEVqXQjfZ7.jpg",
    caption: "3 websites you need right now #college #collegehacks #studytools",
    views: 889776,
    creator: "@1ukas.online",
    creatorUrl: "https://instagram.com/1ukas.online",
  },
  ],
  "visual-hook-plus-device": [
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVc7yrmkRzj/",
    id: "DVc7yrmkRzj",
    dbId: "instagram_instagram_stef0yaps_DVc7yrmkRzj",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVc7yrmkRzj.jpg",
    caption: "SECRET WEBSITES 🤫 #ucla #collegestudent #studytips #websites #ᴇxᴘʟᴏʀᴇᴘᴀɢᴇ",
    views: 2178529,
    creator: "@stef0yaps",
    creatorUrl: "https://instagram.com/stef0yaps",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW-jhlsigdo/",
    id: "DW-jhlsigdo",
    dbId: "instagram_instagram_vibingwithxavierr_DW-jhlsigdo",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW-jhlsigdo.jpg",
    caption: "free apps that feel illegal to know 👀 #spotify #findingmusic #ilovemusic",
    views: 1003936,
    creator: "@vibingwithxavierr",
    creatorUrl: "https://instagram.com/vibingwithxavierr",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWACNUaEQXo/",
    id: "DWACNUaEQXo",
    dbId: "instagram_instagram_caithecheese_DWACNUaEQXo",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWACNUaEQXo.jpg",
    caption: "which one are you going to use? #university #study #frat #college #student",
    views: 2121357,
    creator: "@caithecheese",
    creatorUrl: "https://instagram.com/caithecheese",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWMGdGFE79M/",
    id: "DWMGdGFE79M",
    dbId: "instagram_instagram_jakeezytech_DWMGdGFE79M",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWMGdGFE79M.jpg",
    caption: "Secret website to get free temporary phone numbers online #phonenumbers #freetools",
    views: 1466026,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVWRV2bkxUw/",
    id: "DVWRV2bkxUw",
    dbId: "instagram_instagram_jakeezytech_DVWRV2bkxUw",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVWRV2bkxUw.jpg",
    caption: "Secret Websites that you should know (part 25) Free temporary phone numbers for SMS #freetools #phonenumbers #sms",
    views: 1544896,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWwYXrHE-dE/",
    id: "DWwYXrHE-dE",
    dbId: "instagram_instagram_jakeezytech_DWwYXrHE-dE",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWwYXrHE-dE.jpg",
    caption: "Secret website to watch movies and hangout with your friends online for free just like discord! #tech #ai #productivity #websites #watchparty",
    views: 1519876,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVYmjXoksw-/",
    id: "DVYmjXoksw-",
    dbId: "instagram_instagram_jakeezytech_DVYmjXoksw-",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVYmjXoksw-.jpg",
    caption: "Websites even Google won’t tell you Find every viral sound effect #viral #soundeffects",
    views: 1479420,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DSLWftoE5VH/",
    id: "DSLWftoE5VH",
    dbId: "instagram_instagram_jakeezytech_DSLWftoE5VH",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DSLWftoE5VH.jpg",
    caption: "Secret Websites no one talks about. Play Retro console games of Playstation, xbox for Free #tech #games #gaming #videogames #xbox #playstation #freegames",
    views: 1121667,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DUgJCrek5aa/",
    id: "DUgJCrek5aa",
    dbId: "instagram_instagram_jakeezytech_DUgJCrek5aa",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DUgJCrek5aa.jpg",
    caption: "Secret websites that you should know (part 22) Explore the human anatomy in 3D for free #tech #3d #human #biology #anatomy #learn #students #explore",
    views: 1080990,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DW1MstAE-zg/",
    id: "DW1MstAE-zg",
    dbId: "instagram_instagram_jakeezytech_DW1MstAE-zg",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DW1MstAE-zg.jpg",
    caption: "Secret website to play classic videogames of Playstation, xbox and nintendo for free #games #videogames",
    views: 1029594,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DWvm45ZExXv/",
    id: "DWvm45ZExXv",
    dbId: "instagram_instagram_jakeezytech_DWvm45ZExXv",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DWvm45ZExXv.jpg",
    caption: "Secret websites even google won’t tell you. Get free temporary phone numbers online #freetools #phonenumbers",
    views: 475726,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  {
    platform: "instagram",
    url: "https://www.instagram.com/reel/DVoP2c-E-Ij/",
    id: "DVoP2c-E-Ij",
    dbId: "instagram_instagram_jakeezytech_DVoP2c-E-Ij",
    thumbnail: "https://storage.googleapis.com/trackview-6a3a5.firebasestorage.app/organizations/00JnaavZp41PofxFf3cP/thumbnails/instagram_DVoP2c-E-Ij.jpg",
    caption: "Secret websites that you should know (part 26) Make your own text art for free #ascii #art #createyourown #text",
    views: 452987,
    creator: "@jakeezytech",
    creatorUrl: "https://instagram.com/jakeezytech",
  },
  ],
};
